apiVersion: v1
kind: Namespace
metadata:
  name: pricing
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  namespace: pricing
  labels:
    app: pricing
spec:
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      serviceAccountName: pricing
      containers:
        - name: pricing
          image: pricing
          ports:
            - name: grpc
              containerPort: 3000
          env:
            - name: REDIS_HOST
              value: host.docker.internal
            - name: DB_HOST
              value: host.docker.internal
            - name: VAULT_ADDR
              value: http://host.docker.internal:8200
            - name: ROLE
              value: example
            - name: VAULT_LOGIN_PATH
              value: kubernetes
            - name: PLATFORM
              value: kubernetes
          readinessProbe:
            grpc:
              port: 3000
          livenessProbe:
            grpc:
              port: 3000
          imagePullPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pricing
  namespace: pricing
  labels:
    app: pricing
---
apiVersion: v1
kind: Service
metadata:
  name: pricing
  namespace: pricing
  labels:
    app: pricing
spec:
  type: ClusterIP
  selector:
    app: pricing
  ports:
    - name: grpc
      port: 3000
      targetPort: 3000