apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
  labels:
    app: grpc-gateway
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  template:
    metadata:
      labels:
        app: grpc-gateway
    spec:
      serviceAccountName: grpc-gateway
      containers:
        - name: grpc-gateway
          image: grpc-gateway
          ports:
            - name: http
              containerPort: 8081
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
      volumes:
        - name: grpc-gateway-config
          configMap:
            name: grpc-gateway-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-gateway
  labels:
    app: grpc-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway
  labels:
    app: grpc-gateway
spec:
  type: ClusterIP
  selector:
    app: grpc-gateway
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-gateway
  labels:
    app: grpc-gateway
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: grpc-gateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-gateway-config
data:
  grpc-gateway-config.yaml: |
    services:
      pricing:
        addr: pricing.default:3000