// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type Course struct {
	ID             int64
	Name           string
	Holes          int32
	Lapsed         bool
	Live           bool
	StreetAddress1 string
	City           string
	State          string
	PostalCode     string
	Country        string
	Latitude       sql.NullString
	Longitude      sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Hole struct {
	ID        int64
	CourseID  int64
	Name      string
	Number    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeeBox struct {
	ID        int64
	HoleID    int64
	Color     string
	Yardage   int32
	Rating    float64
	Slope     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
