// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (int64, error)
	GetACourse(ctx context.Context, id int64) (Course, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
}

var _ Querier = (*Queries)(nil)
