// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg *CreateBookingParams) (int64, error)
	GetABooking(ctx context.Context, id int64) (Booking, error)
	GetConfirmedBookingsByDateAndCourse(ctx context.Context, arg *GetConfirmedBookingsByDateAndCourseParams) ([]Booking, error)
	ListUserBookings(ctx context.Context, userID string) ([]Booking, error)
	UpdateAndConfirm(ctx context.Context, arg *UpdateAndConfirmParams) error
	UpdateBooking(ctx context.Context, arg *UpdateBookingParams) error
}

var _ Querier = (*Queries)(nil)
