// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type Schedule struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	CourseID   int64
	StartTime  time.Time
	EndTime    time.Time
	Occurrence int64
	Day        int64
	Buffer     int64
}

type ScheduleOverride struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	CourseID   int64
	StartTime  time.Time
	EndTime    time.Time
	Occurrence int64
	Date       time.Time
	Blocked    bool
}
