// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	GetOverrides(ctx context.Context, arg *GetOverridesParams) ([]GetOverridesRow, error)
	GetSchedule(ctx context.Context, arg *GetScheduleParams) (GetScheduleRow, error)
	GetSchedules(ctx context.Context, courseID int64) ([]GetSchedulesRow, error)
	InsertSchedule(ctx context.Context, arg *InsertScheduleParams) error
}

var _ Querier = (*Queries)(nil)
